name = "RollupTree"
uuid = "04c01c7a-6a3c-48fe-9315-f55725a63c92"
authors = ["James Steven Jenkins <sjenkins@studioj.us> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
