name = "RollupTree"
uuid = "04c01c7a-6a3c-48fe-9315-f55725a63c92"
version = "1.0.0-DEV"
authors = ["James Steven Jenkins <sjenkins@studioj.us> and contributors"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
DataFrames = "1.8.1"
Graphs = "1.13.4"
TestItems = "1.0.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
